### ISSUE TITLE
Using variables in queries results in a blank error response

### ISSUE THREAD

**Issue by briaguya** [rentrop/serverless-postgraphql#1]
Reproduction steps:

1. Follow the setup instructions in the [readme](https://github.com/rentrop/serverless-postgraphql/blob/master/README.md).
2. Query your endpoint to ensure it works:
![screen shot 2017-06-22 at 12 27 18 am](https://user-images.githubusercontent.com/6384156/27418583-9f50b32c-56e1-11e7-9c72-5cb174a9dba1.png)
3. Try doing the same query using query variables instead:
![screen shot 2017-06-22 at 12 22 56 am](https://user-images.githubusercontent.com/6384156/27418600-b13df7e8-56e1-11e7-8e45-8e2d45c2c01e.png)

When running the same query against a local instance of postgraphql using the forum-example schema it works without errors:
![screen shot 2017-06-22 at 12 35 31 am](https://user-images.githubusercontent.com/6384156/27418750-c2024722-56e2-11e7-8b83-b39e25e357fe.png)

**Comment by briaguya** [comment]
After doing a bit more digging I found the request being sent is:
```
{"query":"query ($id: Int!) {
  postById(id: $id) {
    headline
  }
}
","variables":{"id":1}}
```

I'm investigating line 26 of serverless.yml:
`"variables" : "$util.escapeJavaScript($input.path('$.variables'))",`

My thought is that the escapeJavaScript function might not be behaving correctly when parsing an object without quotes around it.

**Comment by briaguya** [comment]
Minor progress: hardcoding the variables in works:
`                  "variables" : {"id": 1},`

**Comment by rentrop** [comment]
@briaguya Thanks. Just merged your PR
