### ISSUE TITLE
v4 PostGraphile Support

### ISSUE THREAD

**Issue by gardner** [rentrop/serverless-postgraphql#8]
Thanks for making this repo. We're evaluating postgraphql on lambda and this has been super helpful. I have been looking at targeting v4 (aka PostGraphile). It looks like there's introspection [caching built in](https://github.com/postgraphql/postgraphql/releases/tag/v4.0.0-alpha2.28) (with "plugin support" that I need to learn more about).

Do you still have energy for this project? Would you be keen to see a PR for v4 support?

**Comment by rentrop** [comment]
At the moment i do not find the time to further develop the project.
If you want to take it from here: Please feel free.
Also there is a version by the PostGraphile-Guys: https://github.com/graphile/postgraphile-lambda-example

**Comment by ryanwestby** [comment]
For anyone else looking for a solution, I have a repo for this here:
https://github.com/ryanwestby/serverless-postgraphile
